name: media_message_initiator
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.1
  helpers: ^1.2.0
  get: ^4.6.5
  video_player: ^2.2.6
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  permission_handler: ^10.2.0
  video_editor: ^2.1.0
  video_thumbnail: ^0.5.3
  gallery_picker: ^0.4.2
  page_transition: ^2.0.9
  flutter_painter: ^1.0.1
  flutter_hsvcolor_picker: ^1.2.3
  flutter_keyboard_size: ^1.0.1
  image_cropping: ^0.0.13
  flutter_emoji_gif_picker: ^0.1.1
  crop_your_image: ^0.7.3
  image: ^3.2.2
  photo_gallery: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
